[versions]
agp = "8.5.1"
datastorePreferences = "1.1.1"
drawbox = "1.0.3"
kotlin = "2.0.0"
ksp = "2.0.0-1.0.23"
googleServices = "4.4.2"

activityCompose = "1.9.1"
composeBom = "2024.06.00"
composeIcon = "1.6.8"
coreKtx = "1.13.1"
lifecycleRuntimeKtx = "2.8.4"
gson = "2.11.0"
koinBom = "3.6.0-wasm-alpha2"
material3 = "1.2.1"
navigation = "2.7.7"
room = "2.6.1"
rangVikalp = "1.0.0-alpha02"
splashScreen = "1.0.1"
firebaseBom = "33.1.2"

espressoCore = "3.6.1"
junit = "4.13.2"
junitVersion = "1.2.1"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
drawbox = { module = "io.ak1:drawbox", version.ref = "drawbox" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
androidx-material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "composeIcon" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "kotlin" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
splash = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom"}
firebase-auth = {module = "com.google.firebase:firebase-auth"}
rang-vikalp = { module = "io.ak1:rang-vikalp", version.ref = "rangVikalp" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
